#!/usr/bin/python3
from sys import argv

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def factorize(num):
    factors = []
    for i in range(2, num + 1):
        while num % i == 0 and is_prime(i):
            factors.append(i)
            num //= i
    return factors

if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: {} filename".format(argv[0]))
        exit(1)
